# Generated by Django 4.0.3 on 2022-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasklog_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
