# Generated by Django 4.0.3 on 2022-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_created_at_taskcomment_published_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='modified_at',
            field=models.DateField(null=True),
        ),
    ]
