# Generated by Django 4.0.3 on 2022-03-25 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at_alter_taskcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 22, 40, 28, 521686)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='modified_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 22, 40, 28, 523731), null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
