# Generated by Django 4.0.3 on 2022-03-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_published_at_taskcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.item'),
        ),
    ]
