# Generated by Django 4.0.3 on 2022-03-25 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_at_alter_taskcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 23, 17, 15, 474790)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='modified_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 23, 17, 15, 476813), null=True),
        ),
    ]
