# Generated by Django 4.0.3 on 2022-03-18 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 20, 10, 45, 914559), null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 20, 10, 45, 916560), null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='modified_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 20, 10, 45, 916560), null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 20, 10, 45, 915560), null=True),
        ),
    ]
